import 'package:flutter/material.dart';

class AppLightColors {
  static const Color white = Color(0xFFFDFDFD);
  static const Color black = Color(0xFF1B1B1B);
  static const Color scaffoldColor = Color(0xFFF7F7FA);
  static const Color primaryColor = Color.fromARGB(255, 181, 25, 19);
  static const Color primaryGreen = Color(0xFF7FBDAE);
  static const Color primaryTextColor = Color(0xFF050506);
  static const Color secondaryTextColor = Color(0xFF808080);
  static const Color secondaryDarkGrey = Color(0xFF8C837B);
  static const Color secondaryLightGrey = Color(0xFFBFB8AF);
  static const Color secondaryLightPink = Color(0xFFE491BC);
  static const Color secondaryDarkGreen = Color(0xFF18952B);
  static const Color secondaryLigthGreen = Color(0xFF6ACD79);
  static const Color secondaryLightPurple = Color(0xFF9B95D6);
  static const Color secondaryDarkBlue = Color(0xFF548EEA);
  static const Color secondaryLightBlue = Color(0xFF8DB4F2);
  static const Color secondaryLightYellow = Color(0xFFFFD166);
  static const Color secondaryLightOrange = Color(0xFFFF985E);
  static const Color auxiliaryRed = Color(0xFFEA1919);
  static const Color auxiliaryOrange = Color(0xFFFF6B00);
  static const Color auxiliaryGreen = Color(0xFF01B801);
  static const Color completedTaskLightGreen = Color(0xFFD7F4DC);
  static const Color backgroundLightGrey = Color(0xFFF5F5F5);
  static const Color darkGrey = Color(0xFF484C52);
  static const Color lightGrey = Color(0xFFBABBC6);
  static const Color lightYellow = Color(0xFFF5F1E9);
  static const Color lightGreen = Color(0xFFE5EBE6);
  static const Color lightPink = Color(0xFFFFE5DF);
  static const Color pink100 = Color(0xFFFFF4F3);
  static const Color taskCardPink = Color(0xFFFFE9E7);
  static const Color blue100 = Color(0xFFDDF3F7);
  static const Color orange100 = Color(0xFFFFF3E8);
  static const Color gray100 = Color(0xFFE0E0E0);
  static const Color darkWhite = Color(0xFFF1F1F1);
  static const Color strokeGrey = Color(0xFFD8D8D8);
  static Color black50 = Color(0xFF1B1B1B).withOpacity(0.5);
  static Color black30 = Color(0xFF1B1B1B).withOpacity(0.3);
  static const Color shimmerColor = Color.fromARGB(255, 240, 240, 240);
  static const Color formInfoBackground = Color(0xFFF2F4F7);
  static const Color formInfoText = Color(0xFF667085);
}
