# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:android)

platform :android do
  desc "Android new version"
  gradle(
      task: 'assemble',
      build_type: 'Release'
  )
  lane :android_firebase_distribution_dev do
    firebase_app_distribution(
        app: "1:826475858519:android:e3675bc944a4caacff7112",
        groups: "android---dev",
        release_notes: "",
        firebase_cli_path: "/usr/local/bin/firebase",
        apk_path: "../build/app/outputs/apk/release/app-release.apk",
        
    )
end
  lane :android_firebase_distribution_prod do
    firebase_app_distribution(
        app: "1:826475858519:android:f24984b62f8e0473ff7112",
        groups: "android---prod",
        release_notes: "PROD",
        firebase_cli_path: "/usr/local/bin/firebase",
        apk_path: "../build/app/outputs/apk/release/app-release.apk"
        # firebase_cli_token: "1//09VnQx0ShwlstCgYIARAAGAkSNwF-L9IroMHT1jjUEkyYN9IVEYUx0wClNuOF5Zh_LpNXTEw_l-wRJiXZ0zCVaK_hwFdzRFXuM6Y"
    )
  end
end